### ISSUE TITLE
sqlalchemy-oauth example not working with sqlalchemy 2.0

### ISSUE THREAD

**Issue by bert2002** [fastapi-users/fastapi-users#1171]
## Describe the bug

When running the oauth example from the github repo it fails due to new type. The error message is the following:

```
sqlalchemy.exc.ArgumentError: Type annotation for "OAuthAccount.id" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
```
Referencing: https://github.com/fastapi-users/fastapi-users/blob/master/examples/sqlalchemy-oauth/app/db.py#L23

## To Reproduce

Run the example in https://github.com/fastapi-users/fastapi-users/blob/master/examples/sqlalchemy-oauth/

## Configuration
 - Python version : 3.8.10
 - FastAPI version : 0.94.0
 - FastAPI Users version : 10.4.0
 - SQLAlchemy: 2.0.3

**Comment by frankie567** [comment]
Can you check that `fastapi-users-db-sqalchemy` dependency is at least on version `5.0.0`?

**Comment by bert2002** [comment]
@frankie567 it seems `fastapi-users-db-sqlalchemy` was not installed.
Before I used 
```
fastapi[all]==0.94.0
fastapi-users[sqlalchemy,oauth]==10.4.0
```
But this did not install `fastapi-users-db-sqlalchemy`. After installing it, it is starting without any problems.
