### ISSUE TITLE
is_verified_by_default unexpected keyword

### ISSUE THREAD

**Issue by bert2002** [fastapi-users/fastapi-users#1172]
## Describe the bug

Setting an Oauth account to verified by default, results in an error. Docs taken from [here](https://fastapi-users.github.io/fastapi-users/10.4/configuration/oauth/#set-is_verified-to-true-by-default).

## To Reproduce

```
app.include_router(
  fastapi_users.get_oauth_router(google_oauth_client, auth_backend, SECRET, is_verified_by_default=True,),
  prefix="/auth/google",
  tags=["auth"],
)
```
Error:

```
    fastapi_users.get_oauth_router(google_oauth_client, auth_backend, SECRET, is_verified_by_default=True,),
TypeError: get_oauth_router() got an unexpected keyword argument 'is_verified_by_default'
```

## Configuration
- FastAPI version : 0.94.0
- FastAPI Users version : 10.4.0

**Comment by frankie567** [comment]
Yes, it was [released on PyPi](https://pypi.org/project/fastapi-users/) 5 days ago, just forgot to publish the notes on GitHub, sorry.
