### ISSUE TITLE
expire_on_commit=False is required for async SQLAlchemy

### ISSUE THREAD

**Issue by gpkc** [fastapi-users/fastapi-users#1175]
## Describe the bug

Since the provided databases interfaces (`SQLAlchemyAccessTokenDatabase` and `SQLAlchemyUserDatabase`) don't explicitly call `refresh` on the created model instances after commit, the error `sqlalchemy.exc.MissingGreenlet` is raised without any hint or description as to why whenever the remainder of the code tries to access some member of the committed model instance.

## To Reproduce

1.  Create a database engine with `expire_on_commit=True`
2. Call some backend method that will try to write to the database and read the result, for example `login`, which will call `write_token`, which writes a new token instance in the database then read `access_token.token`
3. An error will be thrown

## Expected behavior

Either have an explicit documentation that `expire_on_commit` must be set to false on the database connection, or provide an interface that allows refreshing the model instances.

## Configuration
 - Python version : 3.11.2
 - FastAPI version : 0.94.1
 - FastAPI Users version : 10.4.1

**Comment by frankie567** [comment]
Hi @gpkc 👋 

I'm not sure to see where the problem is. It seems that all the examples we show are set  with `expire_on_commit=False`:

* https://fastapi-users.github.io/fastapi-users/10.4/configuration/databases/sqlalchemy/?h=expire_on_commit#create-the-user-model
* https://fastapi-users.github.io/fastapi-users/10.4/configuration/authentication/strategies/database/?h=expire_on_commit#sqlalchemy
* https://fastapi-users.github.io/fastapi-users/10.4/configuration/oauth/?h=expire_on_commit#sqlalchemy
* https://github.com/fastapi-users/fastapi-users/blob/525c1866a7431af2305fe4e1c851a9a721f5a2d0/examples/sqlalchemy/app/db.py#L20

**Comment by gpkc** [comment]
@frankie567 Yes that's correct, but the issue is that someone might not be using this setting in their project at the point where they want to add this package. I just meant that it's not clear this will be a requirement for using the package. Maybe a simple paragraph explaining that it's required and why would work, but I'm not sure. I can open a PR with a suggestion but I wanted to discuss it first :)

**Comment by frankie567** [comment]
Hmm, I see. I've assumed that everybody would already use this setting, as it's the recommended default when using SQLAlchemy with async I/O (see their tutorial: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#synopsis-orm).

I would happily review a PR if you want to clarify this in the docs. A simple callout in https://github.com/fastapi-users/fastapi-users/blob/master/docs/configuration/databases/sqlalchemy.md could probably do the trick.

**Comment by gpkc** [comment]
Yes and it's also recommended on the section about avoiding implicit IO in their docs:
https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-orm-avoid-lazyloads

But some project might be using explicit refreshes, and the error message isn't clear at all about what's wrong.

I'll try to include something on the docs as requested.
