### ISSUE TITLE
Pylance/Pyright type error on full example in docs

### ISSUE THREAD

**Issue by Nerixjk** [fastapi-users/fastapi-users#1262]
## Describe the bug

Error in Pylance when running the example for SQLAlchemy. This error occurs for the User class or the Access Token example for the database strategy due to a type error.

https://fastapi-users.github.io/fastapi-users/12.1/configuration/full-example/
https://fastapi-users.github.io/fastapi-users/12.1/configuration/authentication/strategies/database/

![image](https://github.com/fastapi-users/fastapi-users/assets/32194858/dd7c6c18-67f4-4b3a-b43d-67284cbd9553)

Argument of type "type[User]" cannot be assigned to parameter "user_table" of type "type[UP@SQLAlchemyUserDatabase]" in function "__init__"
  Type "User" cannot be assigned to type "UserProtocol[Unknown]"
    "User" is incompatible with protocol "UserProtocol[Unknown]"
      "__init__" is an incompatible type
        Type "(**kw: Any) -> None" cannot be assigned to type "(*args: Unknown, **kwargs: Unknown) -> None"
          Parameter "*args" has no corresponding parameterPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)

You'll have to forgive me if there are any issues with my bug report; First time using Pydantic and Fastapi (/users).

## To Reproduce

1. Use VS Code with Python and Pylance extension
2. Run 'pip install fastapi-users[sqlalchemy]' and 'pip install aiosqlite' (for sqlite)
3. Copy Full Example in Example > sqlalchemy to VS Code workspace
4. See error in db.py or users.py

## Configuration
 - Python version : 3.11.4
 - FastAPI version : 0.100.1
 - FastAPI Users version : 12.1.0

### FastAPI Users configuration

N/A

## Additional context

N/A

**Comment by frankie567** [comment]
I've released [`v12.1.1`](https://github.com/fastapi-users/fastapi-users/releases/tag/v12.1.1) that should fix this issue.
