### ISSUE TITLE
fastapi depreciation in "full example"

### ISSUE THREAD

**Issue by cargocultprogramming** [fastapi-users/fastapi-users#1312]
## Documentation "full example" contains deprecated on_event call

Setting up the "fully example" demo from the documentation I'm running into a deprecation issue in line 50 of `examples/sqlalchemy-oauth/app/app.py`:

> The method "on_event" in class "FastAPI" is deprecated
>   
>         on_event is deprecated, use lifespan event handlers instead.
> 
>         Read more about it in the
>         [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
>         Pylance
> (method) def on_event(event_type: str) -> ((DecoratedCallable@on_event) -> DecoratedCallable@on_event)
> Add an event handler for the application.
> 
> on_event is deprecated, use lifespan event handlers instead.
> 
> Read more about it in the [FastAPI docs for Lifespan Events](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html).

Depreciation documentation for fastapi is here: https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated

## Configuration
 - Python version : 3.10
 - FastAPI version : 0.104.0
 - FastAPI Users version : 12.1.2

**Comment by cargocultprogramming** [comment]
I'm just noticing that the same call is also present in other examples:

- `examples/beanie/app/app.py`
- `examples/beanie-oauth/app/app.py`
- `examples/sqlalchemy/app/app.py`

**Comment by frankie567** [comment]
That's indeed something we could update. PR welcome!

**Comment by hgalytoby** [comment]
If you want to use "lifespan," you must restrict the FastAPI version to 0.93.0 or higher.

https://github.com/tiangolo/fastapi/releases/tag/0.93.0

**Comment by BrandonGoding** [comment]
I'd be happy to work on a PR for this a few nights this week.
