### ISSUE TITLE
Redis backends can't use 'reset-password' 'verify' 

### ISSUE THREAD

**Issue by izbj** [fastapi-users/fastapi-users#1317]
## Describe the bug

i found i cann't visit a part of routers like 'reset-password' 'verify' when i was use redis backends

## To Reproduce

i saw the code of 'BaseUserManager' i found it only finished JWT code

## Expected behavior

maybe i can use all default routers of fastapi-users when i use redis backends

## Configuration
 - Python version :3.11.6
 - FastAPI version :0.100.1
 - FastAPI Users version :12.1.2

**Comment by hgalytoby** [comment]
> ## Describe the bug
> i found i cann't visit a part of routers like 'reset-password' 'verify' when i was use redis backends
> 
> ## To Reproduce
> i saw the code of 'BaseUserManager' i found it only finished JWT code
> 
> ## Expected behavior
> maybe i can use all default routers of fastapi-users when i use redis backends
> 
> ## Configuration
> * Python version :3.11.6
> * FastAPI version :0.100.1
> * FastAPI Users version :12.1.2

I followed your instructions and tested, but there were actually no issues.

I believe your method of usage is incorrect.

When you use the `reset-password` API, you need to first `call forgot-password` to see the token in the logs. 

![image](https://github.com/fastapi-users/fastapi-users/assets/50397689/6b17ed92-b9ef-406c-8779-cefce41f2fe3)

![image](https://github.com/fastapi-users/fastapi-users/assets/50397689/e3f85795-4b9d-4548-b10d-2efe04d50e38)

Then, you can use that token with the `reset-password` API to reset the password for the associated account.

![image](https://github.com/fastapi-users/fastapi-users/assets/50397689/076897da-f4ef-4743-9987-694ce049f20b)

![image](https://github.com/fastapi-users/fastapi-users/assets/50397689/fa8f7329-054c-4e4d-8657-12f3d2a8f4d1)


The "verify" API follows a similar process as well.

**Comment by izbj** [comment]
> > ## Describe the bug
> > i found i cann't visit a part of routers like 'reset-password' 'verify' when i was use redis backends
> > ## To Reproduce
> > i saw the code of 'BaseUserManager' i found it only finished JWT code
> > ## Expected behavior
> > maybe i can use all default routers of fastapi-users when i use redis backends
> > ## Configuration
> > 
> > * Python version :3.11.6
> > * FastAPI version :0.100.1
> > * FastAPI Users version :12.1.2
> 
> I followed your instructions and tested, but there were actually no issues.
> 
> I believe your method of usage is incorrect.
> 
> When you use the `reset-password` API, you need to first `call forgot-password` to see the token in the logs.
> 
> Then, you can use that token with the `reset-password` API to reset the password for the associated account.
> 
> The `Verify` API follows a similar process as well.
> 
>  20231104_001356.mp4

Watch my video i'm use the RedisStrategy not JWTStrategy

https://github.com/fastapi-users/fastapi-users/assets/38348067/7370d035-a7db-419d-b5f3-c2e4a11f572c

**Comment by hgalytoby** [comment]
> > > ## Describe the bug
> > > i found i cann't visit a part of routers like 'reset-password' 'verify' when i was use redis backends
> > > ## To Reproduce
> > > i saw the code of 'BaseUserManager' i found it only finished JWT code
> > > ## Expected behavior
> > > maybe i can use all default routers of fastapi-users when i use redis backends
> > > ## Configuration
> > > 
> > > * Python version :3.11.6
> > > * FastAPI version :0.100.1
> > > * FastAPI Users version :12.1.2
> > 
> > 
> > I followed your instructions and tested, but there were actually no issues.
> > I believe your method of usage is incorrect.
> > When you use the `reset-password` API, you need to first `call forgot-password` to see the token in the logs.
> > Then, you can use that token with the `reset-password` API to reset the password for the associated account.
> > The `Verify` API follows a similar process as well.
> > 20231104_001356.mp4
> 
> Watch my video i'm use the RedisStrategy not JWTStrategy
> 
>  output.compress-video-online.com.mp4

I'm also using `RedisStrategy`, and I think you haven't been carefully watching my example video.

"The token for the `verify` API is obtained from the `request-verify-token` API, not from the `login` API.

**Comment by izbj** [comment]
> > > > ## Describe the bug
> > > > i found i cann't visit a part of routers like 'reset-password' 'verify' when i was use redis backends
> > > > ## To Reproduce
> > > > i saw the code of 'BaseUserManager' i found it only finished JWT code
> > > > ## Expected behavior
> > > > maybe i can use all default routers of fastapi-users when i use redis backends
> > > > ## Configuration
> > > > 
> > > > * Python version :3.11.6
> > > > * FastAPI version :0.100.1
> > > > * FastAPI Users version :12.1.2
> > > 
> > > 
> > > I followed your instructions and tested, but there were actually no issues.
> > > I believe your method of usage is incorrect.
> > > When you use the `reset-password` API, you need to first `call forgot-password` to see the token in the logs.
> > > Then, you can use that token with the `reset-password` API to reset the password for the associated account.
> > > The `Verify` API follows a similar process as well.
> > > 20231104_001356.mp4
> > 
> > 
> > Watch my video i'm use the RedisStrategy not JWTStrategy
> > output.compress-video-online.com.mp4
> 
> I'm also using `RedisStrategy`, and I think you haven't been carefully watching my example video.
> 
> I just named the parameter `jwt`, not `redis`.
> 
> The token for the `verify` API is obtained from the `request-verify-token` API, not from the `login` API.
> 
> ![image](https://user-images.githubusercontent.com/50397689/280446994-89ee0fec-9040-498f-aa2c-b3d751ba23f8.png)

sorry its my mistake

and i got it now

thanks
