### ISSUE TITLE
Add documentation regarding "Attached to a different loop" error

### ISSUE THREAD

**Issue by frankie567** [fastapi-users/fastapi-users#688]
Following [discussion #663](https://github.com/frankie567/fastapi-users/discussions/663#discussioncomment-1025558) and issue #679, we should add documentation regarding the "Attached to a different loop" error, since it's quite common, especially with Motor.

**Comment by rnd42** [comment]
FYI thanks to the above issues I think I figured out my own variant of this issues.  It seems you can hit the same error when using Gunicorn with Uvicorn workers and the --preload/preload_app option.  I just figured I'd add that here so the eventual documentation can inclued it.

**Comment by scherzocrk** [comment]
I'm facing similar issues too with gunicorn. I don't use --preload option in gunicorn but I'm still getting "Attached to a different loop" error. In my case this is what I'm doing:

- Dockerfile
`CMD ["gunicorn", "--config=gunicorn_conf.py", "--worker-class=uvicorn.workers.UvicornWorker", "main:app"]`

- gunicorn_conf.py

```
import json
import multiprocessing
import os

workers_per_core_str = os.getenv("WORKERS_PER_CORE", "1")
max_workers_str = os.getenv("MAX_WORKERS")
use_max_workers = None
if max_workers_str:
    use_max_workers = int(max_workers_str)
web_concurrency_str = os.getenv("WEB_CONCURRENCY", None)

host = os.getenv("HOST", "0.0.0.0")
port = os.getenv("PORT", "80")
bind_env = os.getenv("BIND", None)
use_loglevel = os.getenv("LOG_LEVEL", "info")
if bind_env:
    use_bind = bind_env
else:
    use_bind = f"{host}:{port}"

cores = multiprocessing.cpu_count()
workers_per_core = float(workers_per_core_str)
default_web_concurrency = workers_per_core * cores
if web_concurrency_str:
    web_concurrency = int(web_concurrency_str)
    assert web_concurrency > 0
else:
    web_concurrency = max(int(default_web_concurrency), 2)
    if use_max_workers:
        web_concurrency = min(web_concurrency, use_max_workers)
accesslog_var = os.getenv("ACCESS_LOG", "-")
use_accesslog = accesslog_var or None
errorlog_var = os.getenv("ERROR_LOG", "-")
use_errorlog = errorlog_var or None
graceful_timeout_str = os.getenv("GRACEFUL_TIMEOUT", "120")
timeout_str = os.getenv("TIMEOUT", "120")
keepalive_str = os.getenv("KEEP_ALIVE", "5")

# Gunicorn config variables
loglevel = use_loglevel
workers = web_concurrency
bind = use_bind
errorlog = use_errorlog
worker_tmp_dir = "/dev/shm"
accesslog = use_accesslog
graceful_timeout = int(graceful_timeout_str)
timeout = int(timeout_str)
keepalive = int(keepalive_str)


# For debugging and testing
log_data = {
    "loglevel": loglevel,
    "workers": workers,
    "bind": bind,
    "graceful_timeout": graceful_timeout,
    "timeout": timeout,
    "keepalive": keepalive,
    "errorlog": errorlog,
    "accesslog": accesslog,
    # Additional, non-gunicorn variables
    "workers_per_core": workers_per_core,
    "use_max_workers": use_max_workers,
    "host": host,
    "port": port,
}
print(json.dumps(log_data))

```

**Comment by frankie567** [comment]
@scherzocrk Could you [start a discussion](https://github.com/fastapi-users/fastapi-users/discussions) and share with us your `main.py` file?

**Comment by scherzocrk** [comment]
Just create a discussion here: https://github.com/fastapi-users/fastapi-users/discussions/711
Thanks for looking into this :)

**Comment by frankie567** [comment]
Since `v8`, FastAPI Users work entirely inside the dependency injection system of FastAPI. Thanks to this, I'm quite confident that we should avoid 99% of "Attached to a different loop" errors.

Closing this for now, but feel free to leave a message below if you encounter the problem in `v8+`.
