### ISSUE TITLE
Support Pydantic SecretStr for authentication backend secrets

### ISSUE THREAD

**Issue by frankie567** [fastapi-users/fastapi-users#701]
As raised in #700.

**Comment by EthanZeigler** [comment]
Unfortunately, this isn't enough. If the user model's `hashed_password` field is a `SecretStr` like the SqlModel ORM wrapper on sqlalchemy, hashing breaks.

I'm working right now on fixing that. While the changes are pretty minimal, the testing changes are fairly substantial as SecretStr doesn't inherit from String. I'm working on having testing for both models.

**Comment by frankie567** [comment]
@EthanZeigler  The original issue was about supporting `SecretStr` for JWT signaptures' secrets.

I don't really see the benefit of using `SecretStr` for `hashed_password`. By default, FastAPI Users takes care of not returning it in the API.

**Comment by EthanZeigler** [comment]
Oh, my bad. I meant to say from the `UserCreate` and `UserUpdate` models for `password`. Think it isn't needed there? I'm totally cool with dropping it if you feel it isn't important as I'm new to fastapi.

**Comment by frankie567** [comment]
Ha, I see, it indeed makes more sense for `password` on `UserCreate` and `UserUpdate`. Well, it could be interesting, but I don't the think the work (and the breaking change) involved worth it.

**Comment by sedrik** [comment]
Hi sorry for raising such an old issue. I ran into an issue today where if you validate your passwords the error message returned contained the password itself which is less than ideal so maybe this could be re-visited? Or maybe a different way of making sure that the password never leaves the server once it has gotten there.

I know about the error handling method of hiding input but that just covers the returned errors and not for example accidentally logging the value during user creation.

Just a different perspective on why this might be a useful change :)
