### ISSUE TITLE
UPDATE_USER_EMAIL_ALREADY_EXISTS is raised when updating e-mail with current address

### ISSUE THREAD

**Issue by ScrimForever** [fastapi-users/fastapi-users#733]
## Describe the bug
When i try to update an user with PATCH method  like - /users/{id} and pass same email, returned 
 "detail": "UPDATE_USER_EMAIL_ALREADY_EXISTS"

but i just like update others variables not email.

## To Reproduce

1. Go to /users/{id}
2. Method PATCH
3. try to update user id with same email
4. See error  "detail": "UPDATE_USER_EMAIL_ALREADY_EXISTS"

## Expected behavior

JSON user updated 

## Configuration
 - Python version : 3.8
 - FastAPI version : 7.0.0
 - FastAPI Users version : 7.0.0

**Comment by frankie567** [comment]
The endpoint was designed as a `PATCH` request, where only fields that should be changed should appear in the payload.

Still, I agree that it may be a bit surprising to get this error when the e-mail doesn't change. I'll improve this!

**Comment by ScrimForever** [comment]
If you not pass email parameter , its return email is required. you cannot send payload.

**Comment by badarsebard** [comment]
Also ran into this same issue. Receive the following error when attempting to patch any single field (not email):
```
{'detail': [{'loc': ['body', 'email'],
   'msg': 'field required',
   'type': 'value_error.missing'},
  {'loc': ['body', 'email'],
   'msg': 'field required',
   'type': 'value_error.missing'}]}
```

This occurs with `/users/{uid}` and `/users/me`. This also looks to be a regression in 7.0.0. Behavior is normal in 6.1.3.

**Comment by frankie567** [comment]
Concerning the "email required" issue when updating, did you make sure you updated your `UserUpdate` model [following v.7.0.0](https://github.com/fastapi-users/fastapi-users/releases/tag/v7.0.0):

> * Your UserUpdate model shouldn't inherit from the base User class anymore. If you have custom fields, you should repeat them in this model. [[Documentation](https://fastapi-users.github.io/fastapi-users/configuration/model/#define-your-models)]
