### ISSUE TITLE
Cookie name not set correctly

### ISSUE THREAD

**Issue by bert2002** [fastapi-users/fastapi-users#765]
## Describe the bug

The cookie has the name of `fastapiusersauth` and not as configured.

## To Reproduce

```
cookie_authentication = CookieAuthentication(secret=SECRET, lifetime_seconds=86400, name="AnewName")
```

Thanks,
bert

**Comment by frankie567** [comment]
The argument to set the cookie name is `cookie_name`, not `name`: https://fastapi-users.github.io/fastapi-users/configuration/authentication/cookie/#configuration

The `name` argument is to set the internal name of the authentication class (mainly useful in case of several authentication methods).
