### ISSUE TITLE
Document the way to create user programmatically

### ISSUE THREAD

**Issue by kamikaze** [fastapi-users/fastapi-users#788]
After upgrading to 8.x.x I've lost the way I could create a user from my python code. I would like to create a bootstrap user on fastapi app start. Is there any way to do that? Thanks

**Comment by kamikaze** [comment]
I had this code to create users:
`
await fastapi_users.create_user(UserCreate(
                email=email,
                password=password,
                is_active=True,
                is_superuser=False,
                is_verified=True,
                organization_id=usr['id']
            ))
`

**Comment by kamikaze** [comment]
Found the following discussion: https://github.com/fastapi-users/fastapi-users/discussions/739
So please treat this issue ticket as a request for a documenting stuff :) Thanks

**Comment by frankie567** [comment]
Available here: https://fastapi-users.github.io/fastapi-users/cookbook/create-user-programmatically/
