### ISSUE TITLE
Incompatible version error with fastapi-jwt-auth[asymmetric] using pipenv

### ISSUE THREAD

**Issue by gikpro** [fastapi-users/fastapi-users#820]
## Describe the bug
The command pipenv lock fail because there are incompatible version in the resolved dependencies.

## To Reproduce
1. Install fastapi-jwt-auth[asymmetric] and fastapi-users[sqlalchemy]
2. pipenv lock
3. I got this error There are incompatible version in the resolved dependencies
pyjwt<2.0.0, >=1.7.1(from fastapi-jwt-auth[asymmetric]==0.5.0 ....
pyjwt==2.30(from fastapi-users[sqlalchemy]==8.1.3

## Expected behavior

pipenv must be lock normally without dependencies conflit

**Comment by frankie567** [comment]
`fastapi-jwt-auth` is a completely different library from FastAPI Users. Both serve the same purpose, so you have to choose which one you want to use.

Concerning the error, `fastapi-jwt-auth` uses an old version of `pyjwt` (<2.0.0) while we use the most up-to-date version (2.3.0). There is nothing I can do here.
