### ISSUE TITLE
Oauth2 cant get a user response

### ISSUE THREAD

**Issue by Hazedd** [fastapi-users/fastapi-users#834]
On fastapi-users v8.1.3 i have tried to implemented the oauth2 example given in the docs (sqlalchemy, sqlite) on python 3.10

i have a jwt and cookie backend, after logging in on google i got a none response. Its not setting a cookie or returning a jwt token. i started the debugger and found the issue below.

The callback function in the get_oauth_router is a checking the backend.name against the state_data. 

![image](https://user-images.githubusercontent.com/20663495/147858316-5eb90a55-fd26-45c5-ab6d-76640da5b6e1.png)

The backand name is 'jwt' but the state_data['authentication_backend'] includes the enum name like: 'AuthenticationBackendName.jwt'.

![image](https://user-images.githubusercontent.com/20663495/147858322-a2ffd7c7-579d-4c55-8a9f-e8e101b8fa78.png)

![image](https://user-images.githubusercontent.com/20663495/147858324-45925f37-ac35-48d1-9389-1b2ef5aab140.png)

this will always return a none. 

after changing this:
![image](https://user-images.githubusercontent.com/20663495/147858609-9daab1df-5fda-4bde-922e-f3c82f917790.png)

to
![image](https://user-images.githubusercontent.com/20663495/147858617-22c67305-660c-488a-aa1a-ce08270e75e7.png)

it seems to be fixed..... looking in to the latest code it seems to be refactored..

**Comment by frankie567** [comment]
Hi @Hazedd! Thank you for raising this. I've fixed it in [`v8.1.5`](https://github.com/fastapi-users/fastapi-users/releases/tag/v8.1.5) to give you time to upgrade to v9.

Still, I can't commit to maintain both versions, so consider upgrading to v9 as soon as possible.

**Comment by Hazedd** [comment]
i have upgraded last night, see you just upgraded the docs 👌
