### ISSUE TITLE
import database in the /examples/sqlalchemy/app/app.py

### ISSUE THREAD

**Issue by exactstat** [fastapi-users/fastapi-users#842]
## Describe the bug
Where: https://github.com/fastapi-users/fastapi-users/blob/master/examples/sqlalchemy/app/app.py
In the app.py:
`from app.db import database`

In the app/db.py: no database instance 

## Expected behavior
Probably

```
from  ...something... import get_async_session

@app.on_event("startup")
async def startup(database=Depends(get_async_session)):
    await database.connect()
```

**Comment by frankie567** [comment]
Nice catch, thanks 🙏 This was a remnant from the previous SQLAlchemy implementation. Fixed!
