### ISSUE TITLE
logout on database strategy is not deleting accesstoken

### ISSUE THREAD

**Issue by Hazedd** [fastapi-users/fastapi-users#847]
When making a logout call and using the database strategy the access token in the database is not deleted.

## To Reproduce

Setup fastapi-user cookie and SQL database strategy 
Register and login
Open SQL database check token table
Logoff
check token table, token still present.

## Expected behavior
When logging out the token should be removed from table.

## Configuration
 - Python version : 3.10
 - FastAPI version : 0.70.1
 - FastAPI Users version : 9.2.0

### FastAPI Users configuration
see [repo](https://github.com/Hazedd/fastapi-users-angular-example) for config.

**Comment by frankie567** [comment]
This should be fixed with [fastapi-users/fastapi-users-db-sqlalchemy@v2.0.4](https://github.com/fastapi-users/fastapi-users-db-sqlalchemy/releases/tag/v2.0.4). You can force-update the sub-depencency with `pip install -U fastapi-users[sqlalchemy2]`

**Comment by frankie567** [comment]
@all-contributors add @Hazedd for bug, docs
