### ISSUE TITLE
how can I implement my own version of  `auth/forgot-password` ?

### ISSUE THREAD

**Issue by DinaTaklit** [fastapi-users/fastapi-users#887]
### Discussed in https://github.com/fastapi-users/fastapi-users/discussions/886

<div type='discussions-op-text'>

<sup>Originally posted by **DinaTaklit** January 19, 2022</sup>
Hello, I have tried to run  `auth/forgot-password` but it does nothing, Could reimplement this end point? how? </div>

**Comment by frankie567** [comment]
@DinaTaklit There is no need to create both an issue and discussion; a discussion is enough :)
