### ISSUE TITLE
[Issue] `sqlalchemy.exc.OperationalError`: (sqlite3.OperationalError) no such table: user

### ISSUE THREAD

**Issue by yezz123** [fastapi-users/fastapi-users#890]
## Describe the bug

While trying the same example that is provided in the examples part I got the issue when I try register function as a parameter i give: 

```JSON
{
  "email": "user@example.com",
  "password": "string"
}
```

## Configuration
 - Python version : 3.9
 - FastAPI version : 0.71.0
 - FastAPI Users version : 9.2.2

## Additional context

the full bug:

```sh
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id, user.email, user.hashed_password, user.is_active, user.is_superuser, user.is_verified 
FROM user 
WHERE lower(user.email) = lower(?)]
[parameters: ('user@example.com',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by abhinavk001** [comment]
It seems that the user table has not been created. Check `create_db_and_tables()` in `db.py` has not been called. But idk how to run that async function.

**Comment by abhinavk001** [comment]
```
@app.on_event("startup")
async def startup():
    await create_db_and_tables()
```
Add this in your main/app.py before declaring routes.

**Comment by yezz123** [comment]
@abhinavk001 Thank you So much I Fix it and everything works fine.

I guess @abhinavk001 its good to open a Pull Request for this and fix it
