### ISSUE TITLE
Inconsistent fields identifying an OAuth account

### ISSUE THREAD

**Issue by ricfri** [fastapi-users/fastapi-users#952]
## Describe the bug

My main problem is that OAuth accounts is not being updated from the callback route, access tokens remaining the same. 

This seems to stem from that the correct OAuth account is not consistently being identified in the same way.

## To Reproduce

Stepping trough the code from the callback route:

1. [In the callback route a new (temporary) OAuth account is always created with a new generated id (UUID)](https://github.com/fastapi-users/fastapi-users/blob/master/fastapi_users/router/oauth.py#L117)
2. [The above OAuth account is passed on to the user manager](https://github.com/fastapi-users/fastapi-users/blob/master/fastapi_users/router/oauth.py#L126)
3. [The user manager finds an existing user, based on the fields oauth_name and account_id of the above oauth](https://github.com/fastapi-users/fastapi-users/blob/master/fastapi_users/manager.py#L190)
5. Begin the process to update existing OAuth account. [OAuth account being identified by the field account_id](https://github.com/fastapi-users/fastapi-users/blob/master/fastapi_users/manager.py#L212). Not checking the field oauth_name as done in 3.
6. [Replace the list of oauth accounts on the user object with a mix of new and old existing OAuth accounts](https://github.com/fastapi-users/fastapi-users/blob/master/fastapi_users/manager.py#L216)
7. [Call the update method of user_db with the above user object as argument](https://github.com/fastapi-users/fastapi-users/blob/master/fastapi_users/manager.py#L217)
8. Using SQLAlchemyUserDatabase, [update based on the id field of the oauth account](https://github.com/fastapi-users/fastapi-users-db-sqlalchemy/blob/main/fastapi_users_db_sqlalchemy/__init__.py#L129). Not using the account_id as in 4.  nor oauth_name as in 3.

Pseudo code to illustrate some of the problems with above:
```
new_oauth_account = {
  id = "789",
  oauth_name = "google",
  account_id = "abc"
}
# Note: identified with fields oauth_name and account_id
existing_user = find_user(new_oauth_account.oauth_name, new_oauth_account.account_id)
old_oauth_account = {
  id = "123",
  oauth_name = "github",
  account_id= "abc"
} = existing_user.oauth_accounts[0]

oauth_db = {"123":  old_oauth_account }

# Note: identified with field account_id
if new_oauth_account.account_id == old_oauth_account.account_id:
  # "abc" == "abc", ok..
  update_oauth_db(new_oauth_account):
  # Note: identified with field id
  if new_oauth_account.id in oauth_db:  # false, id "789" not found. New uuid never exist in db so not updating..
    oauth_db[new_oauth_account.id] = new_oauth_account
```

## Expected behavior

The identifiers of a specific OAuth account should be composite of the OAuth providers name and the account id.

A simple solution should be to [here](https://github.com/fastapi-users/fastapi-users/blob/master/fastapi_users/manager.py#L212 ) change to:
```
...
if existing_oauth_account.account_id == oauth_account.account_id and existing_oauth_account.oauth_name == oauth_account.oauth_name:
    oauth_account.id = existing_oauth_account.id
    updated_oauth_accounts.append(oauth_account)
...
```

Other solutions could be to overload equal function of oauth account and/or remove the id field from oauth accounts. But these could cause breaking change and require more work.

## Configuration
 - FastAPI Users version : 9.3.0
 - fastapi-users-db-sqlalchemy: 3.0.0

**Comment by frankie567** [comment]
Hi @ricfri!

Thank you for your report. I think I get a grasp of what's happening here. 

From what I understand of your example, you seem to have a case where you have two different social providers (Google and GitHub) giving you the same account id? I think I assumed (probably wrongly) that it would be extremely unlikely to have collisions of ID across providers.

Or, for some reasons, you have two OAuth2 clients for the same social provider?

**Comment by ricfri** [comment]
Hi @frankie567! 

Thanks for the quick reply!

Yeah hehe that case should be highly unlikely, not happened to me but might be better to be safe than sorry.

I've been trying to debug for a bit now, so I hope I know what going on 😅 

This is the case that is troubling me: 
The id of the temporary OAuth account, which is a random UUID that was just generated in step 1, is used to try to find the OAuth account which is persisted in the db. These are never the same, so the update fails and I'm stuck with an old access token. See step 5-7 above
