### ISSUE TITLE
cookie + redis -> user_id type error

### ISSUE THREAD

**Issue by phi-friday** [fastapi-users/fastapi-users#958]
## Describe the bug

www-api-1       |   File "/usr/local/lib/python3.10/site-packages/fastapi_users/authentication/authenticator.py", line 136, in current_user_dependency
www-api-1       |     user, _ = await self._authenticate(
www-api-1       |                     │    └ <function Authenticator._authenticate at 0x7fbff974f130>
www-api-1       |                     └ <fastapi_users.authentication.authenticator.Authenticator object at 0x7fbff930f880>
www-api-1       |   File "/usr/local/lib/python3.10/site-packages/fastapi_users/authentication/authenticator.py", line 170, in _authenticate
www-api-1       |     user = await strategy.read_token(token, user_manager)
www-api-1       |                  │        │          │      └ <scripts.database.models.account.manager.user_manager object at 0x7fbff930f220>
www-api-1       |                  │        │          └ 'KNpgAYJBXSa1d59Ptvd7YCVrPP4gLPH4RhBV5JCz_Ac'
www-api-1       |                  │        └ <function RedisStrategy.read_token at 0x7fbff96bf400>
www-api-1       |                  └ <fastapi_users.authentication.strategy.redis.RedisStrategy object at 0x7fbfe290f0a0>
www-api-1       |   File "/usr/local/lib/python3.10/site-packages/fastapi_users/authentication/strategy/redis.py", line 28, in read_token
www-api-1       |     user_uiid = UUID4(user_id)
www-api-1       |                 │     └ b'4c357384-df3d-46f4-88b6-6e91d4d308c8'
www-api-1       |                 └ <class 'pydantic.types.UUID4'>
www-api-1       |   File "/usr/local/lib/python3.10/uuid.py", line 174, in __init__
www-api-1       |     hex = hex.replace('urn:', '').replace('uuid:', '')
www-api-1       |           │   └ <method 'replace' of 'bytes' objects>
www-api-1       |           └ b'4c357384-df3d-46f4-88b6-6e91d4d308c8'
www-api-1       | 
www-api-1       | TypeError: a bytes-like object is required, not 'str'

## To Reproduce

```python
In [8]: c
Out[8]: Redis<ConnectionPool<Connection<host=cache,port=6379,db=0>>>

In [9]: c.get('test')
Out[9]: <coroutine object Redis.execute_command at 0x7f0a45b6fdf0>

In [10]: await c.set('test','123')
Out[10]: True

In [11]: d = await c.get('test')

In [12]: d
Out[12]: b'123'
```

## Configuration
 - Python version : 3.10.4
 - FastAPI version : 0.75.0
 - FastAPI Users version : 9.3.0

### FastAPI Users configuration

```py
class user_base(models.BaseUser):
    ...

class user_create(models.BaseUserCreate):
    ...

class user_update(models.BaseUserUpdate):
    ...

class user_read(user_base):
    ...

class user(user_base, models.BaseUserDB):
    ...
```

## Additional context

redis: 4.2.2
aioredis: from redis.asyncio import Redis
(Aioredis is now in redis-py 4.2.0rc1+)

`get` method of redis return bytes type object.
I'm using it like this temporarily.

```python
class RedisStrategy_patch(RedisStrategy):
    async def read_token(
        self, token: str | None, user_manager: BaseUserManager[models.UC, models.UD]
    ) -> models.UD | None:
        if token is None:
            return None

        user_id = await self.redis.get(token)
        if user_id is None:
            return None
        elif isinstance(user_id, bytes):
            user_id = user_id.decode()

        try:
            user_uiid = UUID4(user_id)
            return await user_manager.get(user_uiid)
        except ValueError:
            return None
        except UserNotExists:
            return None
```

**Comment by frankie567** [comment]
You need to set the `decode_responses` flag to `True` when instantiating Redis client. 

It's specified in the doc: https://fastapi-users.github.io/fastapi-users/configuration/authentication/strategies/redis/

**Comment by phi-friday** [comment]
@frankie567 ah.. so sorry..

**Comment by frankie567** [comment]
Never mind, glad to help 🙂
