### ISSUE TITLE
 ImportError: cannot import name 'BeanieBaseUser' from 'fastapi_users.db'

### ISSUE THREAD

**Issue by galvakojis** [fastapi-users/fastapi-users#978]
## Describe the bug
I am trying to update fastapi-users from version 5 to 10, but it fails at the beginning when I am trying to import `BeanieBaseUser`
`ImportError: cannot import name 'BeanieBaseUser' from 'fastapi_users.db' 
`
my user file looks like this:
```

from beanie import PydanticObjectId
from fastapi_users.db import BeanieBaseUser, BeanieUserDatabase
from fastapi_users import schemas


class User(BeanieBaseUser[PydanticObjectId]):
    nick_name: str

```

## Configuration
 - Python version : 3.8
 - FastAPI version : 0.71.0
 - FastAPI Users version`[beanie]` : =5.1.0 ->10.0.0

**Comment by frankie567** [comment]
There is indeed a circular import issue 😞 I'll fix this right away! Thank you for reporting!

**Comment by frankie567** [comment]
It should be fixed with `fastapi-users[beanie] >= 10.0.1` (check that `fastapi-users-db-beanie == 1.0.1` is installed after that).

**Comment by galvakojis** [comment]
Thank you
but now I have a new one
```
api_1          |   File "/usr/local/lib/python3.8/inspect.py", line 2854, in from_callable
api_1          |     return _signature_from_callable(obj, sigcls=cls,
api_1          |   File "/usr/local/lib/python3.8/inspect.py", line 2228, in _signature_from_callable
api_1          |     raise TypeError('{!r} is not a callable object'.format(obj))
api_1          | TypeError: <fastapi_users_db_beanie.BeanieUserDatabase object at 0x7f16042ad040> is not a callable object
```

**Comment by frankie567** [comment]
@galvakojis I received an e-mail notification with a new comment you posted, but I can't see it. Did you delete it?

**Comment by MJChimal** [comment]
Hi, @frankie567 I'm using the 10.0.5  fastapi_users version, and I have the same problem. I verified the fastapi_users_db_beanie  version and it's 1.0.1.

<img width="538" alt="Captura de Pantalla 2022-05-26 a la(s) 13 31 07" src="https://user-images.githubusercontent.com/10539942/170553240-c73fb15e-2978-409c-a8d9-6842de282f71.png">
<img width="902" alt="Captura de Pantalla 2022-05-26 a la(s) 13 31 33" src="https://user-images.githubusercontent.com/10539942/170553321-b42a4bca-0dec-489d-b55c-1856a0e578ee.png">

Some idea?
