### ISSUE TITLE
Issue with tortoise orm 0.18.1

### ISSUE THREAD

**Issue by Tobi-De** [fastapi-users/fastapi-users#983]
## Describe the bug

There is an error with tortoise orm 0.18.1 using aerich, when I ugrade to 0.19.0  the error goes away but the tortoise orm adapter lock to versions below 0.19.0, there is already a PR from a dependatbot fixing this, it just needs to be reviewed.
The error in question is  `AttributeError: 'NoneType' object has no attribute 'acquire'` when using the aerich upgrade command.

## To Reproduce

1. Install fastapi-users
2. Setup Tortoise orm with fastapi-users
3. Install aerich
4. Initialize your database with aerich
5. Make a DB model change
6. Run aerich upgrade

## Expected behavior

```sh
AttributeError: 'NoneType' object has no attribute 'acquire'
```

## Configuration
 - Python version : 3.10
 - FastAPI version : 0.75.2
 - FastAPI Users version : 9.3.2
 - Tortoise Orm version: 0.18.1

This is not specific to fastapi users and the fix is quite simple.

**Comment by Tobi-De** [comment]
Sorry for the inconvenience, I just saw that the support for tortoise-orm has been dropped, it breaks my heart but I understand.

**Comment by frankie567** [comment]
Hi @Tobi-De!

Really for this 😓 That said, you should be able to easily adapt the previous adapter to the new version, it's quite straightforward.

* You can compare for example the changes for SQLAlchemy : https://github.com/fastapi-users/fastapi-users-db-sqlalchemy/compare/v3.0.1..main
* The most notable change is the addition of two new methods `add_oauth_account` and `update_oauth_account`.

Feel free to ask me if you're stuck or unsure about something!

**Comment by Tobi-De** [comment]
Thanks for your hard work, and I understand, I'm already working on it, should be done by the end of the day, and you're  right, it's really  straightforward, especially when you get a cookiecutter to start with.

**Comment by furkan-guvenc** [comment]
> Thanks for your hard work, and I understand, I'm already working on it, should be done by the end of the day, and you're right, it's really straightforward, especially when you get a cookiecutter to start with.

Have you started yet?

**Comment by Tobi-De** [comment]
> > Thanks for your hard work, and I understand, I'm already working on it, should be done by the end of the day, and you're right, it's really straightforward, especially when you get a cookiecutter to start with.
> 
> Have you started yet?

It's done, you can check it  [here](https://github.com/Tobi-De/fastapi-users-tortoise)

**Comment by enchance** [comment]
@Tobi-De Many thanks for working on the Tortoise-ORM adapter. Mind if I see what your file looks like? I can't seem to get mine to work. I love using TORM since it's based off the Django ORM.

*NOTE: I'm shifting my code from sqlalchemy back to TORM so I might have fucked things up. \*nods\*

**Comment by Tobi-De** [comment]
> @Tobi-De Many thanks for working on the Tortoise-ORM adapter. Mind if I see what your file looks like? I can't seem to get mine to work. I love using TORM since it's based off the Django ORM.
> 
> *NOTE: I'm shifting my code from sqlalchemy back to TORM so I might have fucked things up. *nods*

No problem, I'm a Django user myself and I prefer to work with TORM (I love that abbreviation, I've never seen it before) when using Fastapi.
I don't have a clean example to show right now, try running [this](https://github.com/tobi-de/cookiecutter-fastapi) with the tortoise orm option (which should be the default), that should give you a pretty good example I think, but if you get stuck let me know.

**Comment by enchance** [comment]
> 

Hey this is great you made a cookiecutter out of it! Thanks @Tobi-De I'll play around with it right away. Hopefully I'll have everything settled if not I'll drop you a message. :)

**Comment by enchance** [comment]
@Tobi-De not related to this but would you happen to know how to query an `ArrayField` taken from `from tortoise.contrib.postgres.fields import ArrayField`? Posted here: https://stackoverflow.com/questions/73192631/tortoise-orm-how-to-query-a-postgres-arrayfield-from-tortoise-contrib-postgre.

**Comment by enchance** [comment]
@Tobi-De your repo has been very helpful. I got the things I needed and a few others and added some of my own such as Celery. I hope you find time to keep it updated.
